DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS habit;
DROP TABLE IF EXISTS completion;

CREATE TABLE user (
  id        INTEGER PRIMARY KEY AUTOINCREMENT,
  username  TEXT UNIQUE NOT NULL,
  password  TEXT NOT NULL
);

CREATE TABLE habit (
  id        INTEGER PRIMARY KEY AUTOINCREMENT,
  name      TEXT NOT NULL,
  user_id   INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user(id)
);

CREATE TABLE completion (
  id        INTEGER PRIMARY KEY AUTOINCREMENT,
  timestamp INTEGER NOT NULL,
  habit_id  INTEGER NOT NULL,
  FOREIGN KEY (habit_id) REFERENCES habit(id)
);
